# Generated by Django 5.2.10 on 2026-07-22 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='deploy',
        ),
    ]
