# Generated by Django 5.2.10 on 2026-07-22 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_remove_credential_deploy'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='deploy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='organizations.domain'),
            preserve_default=False,
        ),
    ]
