# Generated by Django 5.2.10 on 2026-07-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_deploy_title_alter_deploy_environment_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploy',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
