# Generated by Django 5.2.10 on 2026-07-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_credential_deploy'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='github_addr',
            field=models.URLField(blank=True, null=True, verbose_name='Github Address'),
        ),
    ]
