# Generated by Django 5.2.10 on 2026-07-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_project_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploy',
            name='github_addr',
        ),
        migrations.AddField(
            model_name='project',
            name='github_addr',
            field=models.URLField(blank=True, null=True, verbose_name='Github Address'),
        ),
    ]
