# Generated by Django 5.2.10 on 2026-07-30 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_remove_deploy_github_addr_project_github_addr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploy',
            name='is_active',
        ),
    ]
