# Generated by Django 5.2.10 on 2026-07-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_remove_deploy_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Maintenance'), (3, 'Inactive')], default=1),
        ),
    ]
