# Generated by Django 5.2.10 on 2026-07-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_add_deploy_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploy',
            name='status',
        ),
        migrations.AddField(
            model_name='domain',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Maintenance'), (3, 'Inactive')], default=1),
        ),
    ]
