# Generated by Django 5.2.10 on 2026-08-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_move_status_to_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='github_addr',
        ),
        migrations.AddField(
            model_name='deploy',
            name='github_repo',
            field=models.URLField(blank=True, null=True, verbose_name='Github Repository'),
        ),
    ]
