# Generated by Django 5.2.10 on 2026-08-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_remove_project_github_addr_deploy_github_repo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploy',
            name='github_repo',
        ),
        migrations.AddField(
            model_name='domain',
            name='github_repo',
            field=models.URLField(blank=True, null=True, verbose_name='Github Repository'),
        ),
    ]
