# Generated by Django 5.2.10 on 2026-07-22 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_obsolete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('services_used', models.TextField()),
                ('deploy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='organizations.deploy')),
            ],
            options={
                'verbose_name': 'Server Detail',
                'verbose_name_plural': 'Server Details',
            },
        ),
    ]
