# Generated by Django 5.2.10 on 2026-07-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverdetails',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='serverdetails',
            name='region',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
