# Generated by Django 5.2.10 on 2026-08-01 10:32

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_serverdetails_name_serverdetails_region'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverdetails',
            name='auto_deploy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serverdetails',
            name='provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serverdetails',
            name='technologies_used',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='serverdetails',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Server Name'),
        ),
        migrations.AlterField(
            model_name='serverdetails',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
