# Generated by Django 5.2.10 on 2026-08-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_serverdetails_auto_deploy_serverdetails_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverdetails',
            name='technologies_used',
        ),
        migrations.AlterField(
            model_name='serverdetails',
            name='services_used',
            field=models.TextField(verbose_name='Service info, port & other notes'),
        ),
    ]
