# Generated by Django 5.2.10 on 2026-08-01 11:08

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_remove_serverdetails_technologies_used_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverdetails',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Technologies used'),
        ),
    ]
