# Generated by Django 5.2.10 on 2026-08-01 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_serverdetails_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverdetails',
            name='tags',
        ),
    ]
